# Generated by Django 6.0.6 on 2026-07-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='holding',
            table=None,
        ),
    ]
