# Generated by Django 6.0.4 on 2026-05-03 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_currency_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_crop_data",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_original",
        ),
    ]
