[project]
name = "budgeteer"
description = "A personal budgeting web application."
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django~=6.0",
    "boto3~=1.43",
    "celery~=5.6",
    "cryptography~=49.0",
    "django-alive~=2.0",
    "django-allauth~=65.16",
    "django-maintenance-mode~=0.19",
    "django-ses~=4.3",
    "django-storages~=1.8",
    "django-unfold~=0.50",
    "epicenv[django]~=1.6",
    "inertia-django~=1.2",
    "hiredis~=3.0", # needed for Django's native cache and sessions
    "psycopg2-binary~=2.9",
    "python-json-logger~=4.1",
    "redis~=8.0", # needed for celery
    "gunicorn~=26.0",
    "django-vite~=3.1",
    "pillow~=12.3",
    "requests~=2.33",
    "ty>=0.0.34",
    "celery-types>=0.26.0",
]

[dependency-groups]
dev = [
    "celery-types",
    "debugpy",
    "django-debug-toolbar",
    "django-test-plus",
    "djlint",
    "ipdb",
    "model-bakery",
    "pytest-cov",
    "pytest-django",
    "ty",
    "readable-log-formatter",
    "ruff",
    "ruff-lsp",
    "zensical",
]

[tool.pytest.ini_options]
addopts = "--nomigrations --ds config.settings.test_runner"

# Python warnings documentation: https://docs.python.org/3/library/warnings.html
filterwarnings = [
    # Set the default behavior for warnings to error, so it forces you to look into fixing them
    "error",
]

[tool.bandit]
exclude_dirs = ["tests", "node_modules"]

[tool.coverage.run]
branch = true
source = ["apps", "config"]
omit = [
    ".venv/*",
    "manage.py",
    "*migrations*",
    "*/tests/*",
]

[tool.coverage.html]
directory = "htmlcov"

[tool.djlint]
indent = 2
profile = "django"
max_line_length = 120
blank_line_after_tag = "endblock,extends,load"
format_css = true
format_js = true
use_gitignore = true
ignore = "H030,H031,H017"
exclude = "base-email.html"

[tool.djlint.js]
indent_size=2

[tool.djlint.css]
indent_size=2

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
    "D",  # pydocstyle
    "S",  # bandit
]
ignore = ["D100", "D101", "D102", "D103", "D104", "D106", "D107", "D203", "D212", ]

[tool.ruff.lint.per-file-ignores]
"**/{tests}/*" = ["S101"]

[tool.ruff.lint.isort.sections]
"django" = ["django"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder", ]

