# Generated by Django 6.0.4 on 2026-05-15 03:58

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_simplefinconnection"),
        ("budget", "0015_add_direct_deposit_payment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["code"], "verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterModelOptions(
            name="simplefinconnection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SimpleFIN Connection",
                "verbose_name_plural": "SimpleFIN Connections",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("simplefin_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("org_name", models.CharField(blank=True, default="", max_length=255)),
                ("org_domain", models.CharField(blank=True, default="", max_length=255)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("balance", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("available_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("balance_as_of", models.DateTimeField(blank=True, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="base.simplefinconnection",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="budget.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["org_name", "name"],
                "unique_together": {("connection", "simplefin_id")},
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("simplefin_id", models.CharField(max_length=255)),
                ("posted_at", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("payee", models.CharField(blank=True, default="", max_length=255)),
                ("memo", models.CharField(blank=True, default="", max_length=500)),
                ("is_pending_at_bank", models.BooleanField(default=False)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("linked", "Linked"), ("ignored", "Ignored")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="base.bankaccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transactions",
                        to="budget.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
                "indexes": [models.Index(fields=["status", "posted_at"], name="base_banktr_status_980c92_idx")],
                "unique_together": {("bank_account", "simplefin_id")},
            },
        ),
    ]
