# Generated by Django 6.0.7 on 2026-08-06 16:53

from decimal import Decimal

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

import apps.base.fields


def seed_current_balances(apps, schema_editor):
    """
    Keep the one balance reading that still exists.

    Every earlier reading was already overwritten in place by a previous sync and cannot be
    recovered. The value sitting on BankAccount right now is real, though, and the next sync would
    replace it before the first snapshot was ever written — so it is captured here instead of
    starting the series from whenever the next cron run happens to land.

    `balance_as_of` is preferred for the timestamp since that is what the bridge reported the
    balance was true at; `updated_at` is the fallback for an account the bridge sent no
    balance-date for.
    """
    BankAccount = apps.get_model("banking", "BankAccount")
    BalanceSnapshot = apps.get_model("banking", "BalanceSnapshot")

    now = timezone.now()
    snapshots = [
        BalanceSnapshot(
            bank_account=account,
            balance=account.balance,
            available_balance=account.available_balance,
            as_of=account.balance_as_of or account.updated_at or now,
        )
        for account in BankAccount.objects.exclude(balance=None)
    ]
    BalanceSnapshot.objects.bulk_create(snapshots, ignore_conflicts=True)


def backfill_last_success_at(apps, schema_editor):
    """
    Seed last_success_at from the attempts we can prove succeeded.

    A connection whose last attempt left no error succeeded, so last_synced_at is also its last
    success. One that is currently carrying an error tells us nothing about when it last worked, so
    it stays null — and sync_status treats a null as "no recent success", which is the safe reading:
    a connection that has been failing since before this migration should show as needing attention
    rather than being granted a grace period it has not earned.
    """
    SimpleFINConnection = apps.get_model("banking", "SimpleFINConnection")
    for connection in SimpleFINConnection.objects.filter(last_sync_error="", last_synced_at__isnull=False):
        connection.last_success_at = connection.last_synced_at
        connection.save(update_fields=["last_success_at"])


class Migration(migrations.Migration):
    replaces = [
        ("banking", "0001_initial"),
        ("banking", "0002_banktransaction_ignore_reason"),
        ("banking", "0003_rename_legacy_base_tables"),
        ("banking", "0004_balancesnapshot"),
        ("banking", "0005_seed_current_balances"),
        ("banking", "0006_simplefinconnection_last_success_at_and_more"),
        ("banking", "0007_backfill_last_success_at"),
        ("banking", "0008_alter_bankaccount_connection_and_more"),
        ("banking", "0009_bankaccount_budget"),
    ]

    dependencies = [
        ("base", "0005_drop_last_sync_status"),
        ("budget", "0018_sinking_fund_table"),
        ("budget", "0031_remove_recurringtransaction_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SimpleFINConnection",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("label", models.CharField(blank=True, default="", max_length=100)),
                        ("access_url", apps.base.fields.EncryptedTextField()),
                        ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                        ("last_sync_error", models.TextField(blank=True, default="")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="simplefin_connections",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "base_simplefinconnection",
                        "ordering": ["-created_at"],
                        "verbose_name": "SimpleFIN Connection",
                        "verbose_name_plural": "SimpleFIN Connections",
                    },
                ),
                migrations.CreateModel(
                    name="BankAccount",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("simplefin_id", models.CharField(max_length=255)),
                        ("name", models.CharField(max_length=255)),
                        ("org_name", models.CharField(blank=True, default="", max_length=255)),
                        ("org_domain", models.CharField(blank=True, default="", max_length=255)),
                        ("currency", models.CharField(default="USD", max_length=3)),
                        ("balance", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                        (
                            "available_balance",
                            models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                        ),
                        ("balance_as_of", models.DateTimeField(blank=True, null=True)),
                        ("is_hidden", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "connection",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="bank_accounts",
                                to="banking.simplefinconnection",
                            ),
                        ),
                        (
                            "payment_method",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="bank_accounts",
                                to="budget.paymentmethod",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "base_bankaccount",
                        "ordering": ["org_name", "name"],
                        "unique_together": {("connection", "simplefin_id")},
                    },
                ),
                migrations.CreateModel(
                    name="BankTransaction",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("simplefin_id", models.CharField(max_length=255)),
                        ("posted_at", models.DateTimeField()),
                        ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                        ("description", models.CharField(blank=True, default="", max_length=500)),
                        ("payee", models.CharField(blank=True, default="", max_length=255)),
                        ("memo", models.CharField(blank=True, default="", max_length=500)),
                        ("is_pending_at_bank", models.BooleanField(default=False)),
                        ("raw", models.JSONField(blank=True, default=dict)),
                        (
                            "status",
                            models.CharField(
                                choices=[("pending", "Pending"), ("linked", "Linked"), ("ignored", "Ignored")],
                                default="pending",
                                max_length=10,
                            ),
                        ),
                        ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                        ("last_seen_at", models.DateTimeField(auto_now=True)),
                        (
                            "bank_account",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="bank_transactions",
                                to="banking.bankaccount",
                            ),
                        ),
                        (
                            "transaction",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="bank_transaction",
                                to="budget.transaction",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "base_banktransaction",
                        "ordering": ["-posted_at"],
                        "indexes": [models.Index(fields=["status", "posted_at"], name="base_banktr_status_980c92_idx")],
                        "unique_together": {("bank_account", "simplefin_id")},
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="ignore_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER INDEX IF EXISTS "base_bankt_status_55b5fb_idx" RENAME TO "banking_ban_status_25ad4b_idx";',
                        'ALTER INDEX IF EXISTS "base_banktr_status_980c92_idx" RENAME TO "banking_ban_status_25ad4b_idx";',
                    ],
                    reverse_sql='ALTER INDEX IF EXISTS "banking_ban_status_25ad4b_idx" RENAME TO "base_banktr_status_980c92_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="banktransaction",
                    new_name="banking_ban_status_25ad4b_idx",
                    old_name="base_banktr_status_980c92_idx",
                ),
            ],
        ),
        migrations.AlterModelTable(
            name="bankaccount",
            table=None,
        ),
        migrations.AlterModelTable(
            name="banktransaction",
            table=None,
        ),
        migrations.AlterModelTable(
            name="simplefinconnection",
            table=None,
        ),
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=2, max_digits=16)),
                ("available_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                (
                    "as_of",
                    models.DateTimeField(help_text="The bridge's balance-date, or the sync time if it sent none."),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_snapshots",
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of"],
                "indexes": [models.Index(fields=["bank_account", "-as_of"], name="balance_snapshot_account_asof")],
                "constraints": [
                    models.UniqueConstraint(fields=("bank_account", "as_of"), name="unique_balance_snapshot_per_as_of")
                ],
            },
        ),
        migrations.RunPython(
            code=seed_current_balances,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="simplefinconnection",
            name="last_success_at",
            field=models.DateTimeField(blank=True, help_text="Last attempt that returned data.", null=True),
        ),
        migrations.AlterField(
            model_name="simplefinconnection",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, help_text="Last attempt, successful or not.", null=True),
        ),
        migrations.RunPython(
            code=backfill_last_success_at,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="banking.simplefinconnection",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("connection__isnull", True)),
                fields=("simplefin_id",),
                name="unique_imported_bank_account",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_bank_accounts",
                to="budget.budget",
            ),
        ),
    ]
