# Generated by Django 6.0.4 on 2026-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="ignore_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
