# Generated by Django 6.0.7 on 2026-08-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0003_rename_legacy_base_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=2, max_digits=16)),
                ("available_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                (
                    "as_of",
                    models.DateTimeField(help_text="The bridge's balance-date, or the sync time if it sent none."),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_snapshots",
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of"],
                "indexes": [models.Index(fields=["bank_account", "-as_of"], name="balance_snapshot_account_asof")],
                "constraints": [
                    models.UniqueConstraint(fields=("bank_account", "as_of"), name="unique_balance_snapshot_per_as_of")
                ],
            },
        ),
    ]
