# Generated by Django 6.0.7 on 2026-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0005_seed_current_balances"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplefinconnection",
            name="last_success_at",
            field=models.DateTimeField(blank=True, help_text="Last attempt that returned data.", null=True),
        ),
        migrations.AlterField(
            model_name="simplefinconnection",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, help_text="Last attempt, successful or not.", null=True),
        ),
    ]
