# Generated by Django 6.0.7 on 2026-08-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0007_backfill_last_success_at"),
        ("budget", "0031_remove_recurringtransaction_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="banking.simplefinconnection",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("connection__isnull", True)),
                fields=("simplefin_id",),
                name="unique_imported_bank_account",
            ),
        ),
    ]
