# Generated by Django 6.0.7 on 2026-08-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0008_alter_bankaccount_connection_and_more"),
        ("budget", "0031_remove_recurringtransaction_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_bank_accounts",
                to="budget.budget",
            ),
        ),
    ]
