# Generated by Django 6.0.7 on 2026-08-06 16:52

from decimal import Decimal

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def remove_recurring_instance_lines(apps, schema_editor):
    TransactionLine = apps.get_model("budget", "TransactionLine")
    TransactionLine.objects.filter(transaction__recurring__isnull=False).delete()


def assign_payment_methods_to_budgets(apps, schema_editor):
    PaymentMethod = apps.get_model("budget", "PaymentMethod")
    BudgetMembership = apps.get_model("budget", "BudgetMembership")

    for pm in PaymentMethod.objects.all():
        membership = BudgetMembership.objects.filter(user_id=pm.user_id, role="owner").first()
        if not membership:
            membership = BudgetMembership.objects.filter(user_id=pm.user_id).first()
        if membership:
            pm.budget_id = membership.budget_id
            pm.save(update_fields=["budget"])
        else:
            pm.delete()


def backfill_amount_usd(apps, schema_editor):
    TransactionLine = apps.get_model("budget", "TransactionLine")
    TransactionLine.objects.all().update(amount_usd=models.F("amount"))


def backfill_lines(apps, schema_editor):
    """Add a TransactionLine to every recurring Transaction that has none."""
    Transaction = apps.get_model("budget", "Transaction")
    TransactionLine = apps.get_model("budget", "TransactionLine")
    qs = Transaction.objects.filter(recurring__isnull=False, lines__isnull=True).select_related("recurring")
    lines = []
    for txn in qs.iterator():
        rt = txn.recurring
        lines.append(
            TransactionLine(
                transaction=txn,
                category_id=rt.category_id,
                amount=rt.amount,
                amount_usd=rt.amount,
            )
        )
        if len(lines) >= 500:
            TransactionLine.objects.bulk_create(lines)
            lines = []
    if lines:
        TransactionLine.objects.bulk_create(lines)


def noop_reverse(apps, schema_editor):
    pass


def backfill_paid_date(apps, schema_editor):
    """Where is_paid=True but paid_date is null, copy due_date into paid_date so we don't lose the 'paid' signal."""
    Transaction = apps.get_model("budget", "Transaction")
    Transaction.objects.filter(is_paid=True, paid_date__isnull=True).update(paid_date=F("due_date"))


def noop_reverse_0017(apps, schema_editor):
    pass


def backfill_sinking_funds(apps, schema_editor):
    Category = apps.get_model("budget", "Category")
    SinkingFund = apps.get_model("budget", "SinkingFund")
    rows = []
    for cat in Category.objects.filter(is_sinking_fund=True).iterator():
        if cat.sinking_fund_target is None:
            continue
        rows.append(
            SinkingFund(
                category_id=cat.pk,
                target=cat.sinking_fund_target,
                due_date=cat.sinking_fund_due_date,
                ongoing=cat.sinking_fund_ongoing,
                monthly_goal=cat.sinking_fund_monthly_goal,
            )
        )
        if len(rows) >= 500:
            SinkingFund.objects.bulk_create(rows)
            rows = []
    if rows:
        SinkingFund.objects.bulk_create(rows)


def noop_reverse_0018(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    replaces = [
        ("budget", "0001_initial"),
        ("budget", "0002_remove_budget_name_description"),
        ("budget", "0003_remove_recurring_instance_lines"),
        ("budget", "0004_add_category_budget"),
        ("budget", "0005_add_payment_method"),
        ("budget", "0006_category_monthly_budget"),
        ("budget", "0007_recurringtransaction_payment_method"),
        ("budget", "0008_budget_name"),
        ("budget", "0009_paymentmethod_budget"),
        ("budget", "0010_category_sinking_fund"),
        ("budget", "0011_transaction_transaction_type"),
        ("budget", "0012_category_sinking_fund_ongoing"),
        ("budget", "0013_add_currency_to_transaction"),
        ("budget", "0014_alter_category_unique_together_category_parent_and_more"),
        ("budget", "0015_add_direct_deposit_payment_type"),
        ("budget", "0016_backfill_recurring_lines"),
        ("budget", "0017_drop_transaction_is_paid"),
        ("budget", "0018_sinking_fund_table"),
        ("budget", "0019_alter_transactionline_amount_usd"),
        ("budget", "0020_goal_delete_sinkingfund"),
        ("budget", "0021_transaction_transfer_partner_alter_goal_category"),
        ("budget", "0022_category_is_system"),
        ("budget", "0023_transaction_budget_month_payschedule"),
        ("budget", "0024_payschedule_category"),
        ("budget", "0025_remove_payschedule_anchor_day_and_more"),
        ("budget", "0026_category_rollover"),
        ("budget", "0027_category_base_amount_category_rollover_start"),
        ("budget", "0028_payschedule_payment_method"),
        ("budget", "0029_transaction_unique_pay_schedule_instance_per_due_date_and_more"),
        ("budget", "0030_recurringtransaction_recurring_interval_at_least_one"),
        ("budget", "0031_remove_recurringtransaction_is_active"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")], default="member", max_length=10
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="budget.budget"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("budget", "user")},
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="members",
            field=models.ManyToManyField(
                related_name="budgets", through="budget.BudgetMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(choices=[("income", "Income"), ("expense", "Expense")], max_length=10),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="budget.budget"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("every_n_months", "Every N Months"),
                            ("annually", "Annually"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of months between occurrences. Used only when frequency is 'Every N Months'.",
                    ),
                ),
                ("start_date", models.DateField(help_text="Date of the first occurrence.")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="No new instances are generated after this date.", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("generated_through", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to="budget.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_transactions",
                        to="budget.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recurring_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="budget.budget"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="budget.recurringtransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="TransactionLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_lines",
                        to="budget.category",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="budget.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["category__name"],
            },
        ),
        migrations.RemoveField(
            model_name="budget",
            name="description",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="name",
        ),
        migrations.RunPython(
            code=remove_recurring_instance_lines,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="CategoryBudget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(help_text="First day of the month this assignment applies to.")),
                ("assigned", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="category_budgets", to="budget.budget"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_budgets",
                        to="budget.category",
                    ),
                ),
            ],
            options={
                "ordering": ["month", "category__name"],
                "unique_together": {("budget", "category", "month")},
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="budget.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="monthly_budget",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_transactions",
                to="budget.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="budget.budget",
            ),
        ),
        migrations.RunPython(
            code=assign_payment_methods_to_budgets,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payment_methods", to="budget.budget"
            ),
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="user",
        ),
        migrations.AddField(
            model_name="category",
            name="is_sinking_fund",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="sinking_fund_target",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="sinking_fund_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="category",
            name="sinking_fund_ongoing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="sinking_fund_monthly_goal",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="transaction",
            name="exchange_rate_to_usd",
            field=models.DecimalField(decimal_places=8, default=Decimal("1"), max_digits=20),
        ),
        migrations.AddField(
            model_name="transactionline",
            name="amount_usd",
            field=models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=14),
        ),
        migrations.RunPython(
            code=backfill_amount_usd,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent category. Subcategories cannot have children of their own.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="budget.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("budget", "name", "category_type"),
                name="unique_root_category_per_budget_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="unique_subcategory_per_parent",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("direct_deposit", "Direct Deposit"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            code=backfill_lines,
            reverse_code=noop_reverse,
        ),
        migrations.RunPython(
            code=backfill_paid_date,
            reverse_code=noop_reverse_0017,
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_paid",
        ),
        migrations.CreateModel(
            name="SinkingFund",
            fields=[
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sinking_fund",
                        serialize=False,
                        to="budget.category",
                    ),
                ),
                ("target", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("ongoing", models.BooleanField(default=False)),
                ("monthly_goal", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.RunPython(
            code=backfill_sinking_funds,
            reverse_code=noop_reverse_0018,
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_sinking_fund",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sinking_fund_target",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sinking_fund_due_date",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sinking_fund_ongoing",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sinking_fund_monthly_goal",
        ),
        migrations.AlterField(
            model_name="transactionline",
            name="amount_usd",
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.RenameModel(
            old_name="SinkingFund",
            new_name="Goal",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_partner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="budget.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="goal",
                serialize=False,
                to="budget.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget_month",
            field=models.DateField(
                blank=True,
                help_text="First day of the budget month this transaction funds; overrides paid_date bucketing.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PaySchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this income source, e.g. the job it belongs to.", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Once a month"),
                            ("semimonthly", "Twice a month"),
                            ("biweekly", "Every two weeks"),
                            ("weekly", "Weekly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        blank=True,
                        help_text="A reference payday, used to project every-two-weeks / weekly paydays.",
                        null=True,
                    ),
                ),
                (
                    "allocation_offset_months",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = income funds the month it's received; 1 = funds the following month."
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approximate paycheck amount. Also used to match income to this schedule.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "match_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If the transaction description or bank payee contains this text, it matches this schedule.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pay_schedules", to="budget.budget"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Income category a matched paycheck should be recorded under.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_schedules",
                        to="budget.category",
                    ),
                ),
                (
                    "anchor_1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginning", "Beginning of the month"),
                            ("middle", "Middle of the month"),
                            ("end", "End of the month"),
                        ],
                        default="",
                        help_text="First payday of the month (monthly / twice-a-month schedules).",
                        max_length=10,
                    ),
                ),
                (
                    "anchor_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginning", "Beginning of the month"),
                            ("middle", "Middle of the month"),
                            ("end", "End of the month"),
                        ],
                        default="",
                        help_text="Second payday of the month, for twice-a-month schedules.",
                        max_length=10,
                    ),
                ),
                ("generated_through", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account a paycheck from this schedule is deposited into.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_schedules",
                        to="budget.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="pay_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="budget.payschedule",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="rollover",
            field=models.BooleanField(
                default=False,
                help_text="Carry this category's leftover balance forward into the next month instead of resetting it.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Recurring amount budgeted to a rollover category each month; leftover accrues on top.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="rollover_start",
            field=models.DateField(
                blank=True,
                help_text="First month (1st) the rollover base begins accruing. Set when rollover is enabled.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pay_schedule__isnull", False)),
                fields=("pay_schedule", "due_date"),
                name="unique_pay_schedule_instance_per_due_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurring__isnull", False)),
                fields=("recurring", "due_date"),
                name="unique_recurring_instance_per_due_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1)), name="recurring_interval_at_least_one"
            ),
        ),
        migrations.RemoveField(
            model_name="recurringtransaction",
            name="is_active",
        ),
    ]
