# Generated by Django 6.1 on 2026-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_retire_transfers_category_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_opening_balance",
            field=models.BooleanField(
                default=False,
                help_text="Savings that already existed when a goal was created, not money that moved. It gives the goal its starting balance and is excluded from every monthly flow figure.",
            ),
        ),
    ]
