# Generated by Django 6.0.4 on 2026-05-03 20:09

from decimal import Decimal

from django.db import migrations, models


def backfill_amount_usd(apps, schema_editor):
    TransactionLine = apps.get_model("budget", "TransactionLine")
    TransactionLine.objects.all().update(amount_usd=models.F("amount"))


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0012_category_sinking_fund_ongoing"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="transaction",
            name="exchange_rate_to_usd",
            field=models.DecimalField(decimal_places=8, default=Decimal("1"), max_digits=20),
        ),
        migrations.AddField(
            model_name="transactionline",
            name="amount_usd",
            field=models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=14),
        ),
        migrations.RunPython(backfill_amount_usd, migrations.RunPython.noop),
    ]
