# Generated by Django 6.0.5 on 2026-06-16 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_alter_transactionline_amount_usd"),
    ]

    operations = [
        migrations.RenameModel(old_name="SinkingFund", new_name="Goal"),
    ]
