# Generated by Django 6.0.7 on 2026-07-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0022_category_is_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="budget_month",
            field=models.DateField(
                blank=True,
                help_text="First day of the budget month this transaction funds; overrides paid_date bucketing.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PaySchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this income source, e.g. the job it belongs to.", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Once a month"),
                            ("semimonthly", "Twice a month"),
                            ("biweekly", "Every two weeks"),
                            ("weekly", "Weekly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "anchor_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Day of the month of the (first) payday. Use 31 for the last day of the month.",
                        null=True,
                    ),
                ),
                (
                    "anchor_day_2",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Second payday day-of-month, for twice-a-month schedules.", null=True
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        blank=True,
                        help_text="A reference payday, used to project every-two-weeks / weekly paydays.",
                        null=True,
                    ),
                ),
                (
                    "allocation_offset_months",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = income funds the month it's received; 1 = funds the following month."
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approximate paycheck amount, used to match income to this schedule.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "match_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If the transaction description or bank payee contains this text, it matches this schedule.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pay_schedules", to="budget.budget"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
