# Generated by Django 6.0.7 on 2026-07-30 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0023_transaction_budget_month_payschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="payschedule",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Income category a matched paycheck should be recorded under.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pay_schedules",
                to="budget.category",
            ),
        ),
    ]
