# Generated by Django 6.0.7 on 2026-07-31 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0024_payschedule_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payschedule",
            name="anchor_day",
        ),
        migrations.RemoveField(
            model_name="payschedule",
            name="anchor_day_2",
        ),
        migrations.AddField(
            model_name="payschedule",
            name="anchor_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginning", "Beginning of the month"),
                    ("middle", "Middle of the month"),
                    ("end", "End of the month"),
                ],
                default="",
                help_text="First payday of the month (monthly / twice-a-month schedules).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payschedule",
            name="anchor_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginning", "Beginning of the month"),
                    ("middle", "Middle of the month"),
                    ("end", "End of the month"),
                ],
                default="",
                help_text="Second payday of the month, for twice-a-month schedules.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payschedule",
            name="generated_through",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pay_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="budget.payschedule",
            ),
        ),
        migrations.AlterField(
            model_name="payschedule",
            name="expected_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Approximate paycheck amount. Also used to match income to this schedule.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
