# Generated by Django 6.0.7 on 2026-07-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0025_remove_payschedule_anchor_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="rollover",
            field=models.BooleanField(
                default=False,
                help_text="Carry this category's leftover balance forward into the next month instead of resetting it.",
            ),
        ),
    ]
