# Generated by Django 6.0.7 on 2026-07-31 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0026_category_rollover"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Recurring amount budgeted to a rollover category each month; leftover accrues on top.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="rollover_start",
            field=models.DateField(
                blank=True,
                help_text="First month (1st) the rollover base begins accruing. Set when rollover is enabled.",
                null=True,
            ),
        ),
    ]
