# Generated by Django 6.0.7 on 2026-08-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0027_category_base_amount_category_rollover_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="payschedule",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Account a paycheck from this schedule is deposited into.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pay_schedules",
                to="budget.paymentmethod",
            ),
        ),
    ]
