# Generated by Django 6.0.7 on 2026-08-04 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0028_payschedule_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pay_schedule__isnull", False)),
                fields=("pay_schedule", "due_date"),
                name="unique_pay_schedule_instance_per_due_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurring__isnull", False)),
                fields=("recurring", "due_date"),
                name="unique_recurring_instance_per_due_date",
            ),
        ),
    ]
