# Generated by Django 6.0.7 on 2026-08-04 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0029_transaction_unique_pay_schedule_instance_per_due_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1)), name="recurring_interval_at_least_one"
            ),
        ),
    ]
