# Generated by Django 6.0.7 on 2026-08-04 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0030_recurringtransaction_recurring_interval_at_least_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringtransaction",
            name="is_active",
        ),
    ]
